version: '3'

services:
  cassandra:
    image: cassandra:3
    restart: on-failure
    volumes:
      - cassandra_data:/var/lib/cassandra
    ports:
      - 7000:7000
      - 7001:7001
      - 7199:7199
      - 9042:9042
      - 9160:9160
      
volumes:
  cassandra_data: